var fs = require('fs'),
	util = require('util'),
	info = require('./package.json'),
	async = require('async'),
	sql = require('sql');

var supportedDialects = {
	mysql: 1,
	pg: 1
};

/**
 * @param {Object} options
 * @param {String} options.dialect Either "mysql" or "pg"
 * @param {String} options.dsn The DSN to use to connect to the database
 * @param {String} options.schema The name of the schema/database to extract from
 * @param {String} [options.indent] String to use for indentation of generated code, defaults to "\t"
 * @param {String|Number} [options.outputFile] Filename to write to, or the number 1 to write to stdout
 * @param {Boolean} [options.camelize] Convert underscored names to camel case ("foo_bar" -> "fooBar")
 * @param {String} [options.eol] End-of-line character, defaults to "\n"
 * @param {String} [options.mode] The permission mode of the output file, defaults to 0644
 * @param {String} [options.encoding] The encoding of the output file, defaults to "utf8"
 * @param {String} [options.prepend] String to prepend to the beginning of the generated output
 * @param {String} [options.append] String to append to the end of the generated output
 * @param {String} [options.omitComments] Omit autogenerated comments
 * @param {function} [options.log] Logging function
 * @param {Function} [callback]
 */
module.exports = function(options, callback) {
	options = options || {};

	if (!options.dsn) {
		callback && callback(new Error('options.dsn is required'));
		return;
	}
	if (!options.dialect) {
		var match = /^(mysql|postgres)/i.exec(options.dsn);
		if (!match) {
			callback && callback(new Error('options.dialect is required'));
			return;
		}

		options.dialect = match[1].toLowerCase() === 'mysql' ? 'mysql' : 'pg';
	}

	options.dialect = options.dialect.toLowerCase();

	if (!supportedDialects[options.dialect]) {
		callback && callback(new Error('options.dialect must be either "mysql" or "pg"'));
		return;
	}

	options.eol = options.eol || '\n';
	options.encoding = options.encoding || 'utf8';
	options.mode = options.mode || 0644;
	options.indent = options.indent || '\t';

	function camelize(name) {
		return !options.camelize ? name : name.replace(/_(.)/g, function(all, c) {
			return c.toUpperCase();
		});
	}

	function runQuery(query, callback) {
		query = query.toQuery();
		log('debug', 'QUERY: ' + query.text + ' :: ' + util.inspect(query.values));
		switch (options.dialect) {
			case 'mysql':
				client.query(query.text, query.values, callback);
				break;
			case 'pg':
				client.query(query.text, query.values, function(err, result) {
					callback(err, result && result.rows);
				});
				break;
		}
	}

	function write() {
		var string = [].slice.call(arguments, 0, -1)
				.map(function(obj) { return (obj || '').toString(); })
				.filter(function(message) { return !!message; })
				.join(options.eol) + options.eol,
			callback = arguments[arguments.length - 1],
			buffer = new Buffer(string, options.encoding);

		if (fd) {
			fs.write(fd, buffer, 0, buffer.length, null, function(err, written) {
				stats.bytesWritten += (written || 0);
				callback(err);
			});
		} else {
			stats.buffer += buffer.toString();
			stats.bytesWritten += buffer.length;
			process.nextTick(callback);
		}
	}

	function getListOfTables(callback) {
		var query = tables
			.select(tables.name.as('name'))
			.from(tables);

		switch (options.dialect) {
			case 'mysql':
				query = query.where(tables.schema.equals(options.database));
				break;
			case 'pg':
				query = query
					.where(tables.schema.equals(options.schema))
					.and(tables.catalog.equals(options.database));
				break;
		}

		query = query.order(tables.name);

		runQuery(query, function(err, rows) {
			if (err) {
				callback(err);
				return;
			}

			callback(null, rows.map(function(row) {
				return row.name;
			}));
		});
	}

	function getListOfColumns(tableName, callback) {
		var query = columns
			.select(
				columns.name.as('name'),
				columns.isNullable.as('nullable'),
				columns.defaultValue.as('default_value'),
				columns.type.as('type')
			)
			.from(columns)
			.where(columns.tableName.equals(tableName));

		switch (options.dialect) {
			case 'mysql':
				query = query.and(columns.tableSchema.equals(options.database));
				break;
			case 'pg':
				query = query
					.and(columns.tableSchema.equals(options.schema))
					.and(columns.tableCatalog.equals(options.database));
				break;
		}

		query = query.order(columns.ordinalPosition);

		runQuery(query, function(err, results) {
			if (err) {
				callback(err);
				return;
			}

			callback(null, results);
		});
	}

	var log = options.log || function() {},
		fd = null,
		client = null,
		tableNames = null,
		stats = {
			start: new Date(),
			end: null,
			elapsed: null,
			written: 0,
			buffer: ''
		},
		db = require(options.dialect),
		columns,
		tables;

	switch (options.dialect) {
		case 'mysql':
			client = db.createConnection(options.dsn);
			options.database = options.database || client.config.database;
			sql.setDialect('mysql');
			columns = sql.define({
				name: 'COLUMNS',
				schema: 'information_schema',
				columns: [
					{ name: 'TABLE_SCHEMA', property: 'tableSchema' },
					{ name: 'TABLE_NAME', property: 'tableName' },
					{ name: 'COLUMN_NAME', property: 'name' },
					{ name: 'ORDINAL_POSITION', property: 'ordinalPosition' },
					{ name: 'DATA_TYPE', property: 'type' },
					{ name: 'CHARACTER_MAXIMUM_LENGTH', property: 'charLength' },
					{ name: 'COLUMN_DEFAULT', property: 'defaultValue' },
					{ name: 'IS_NULLABLE', property: 'isNullable' }
				]
			});
			tables = sql.define({
				name: 'TABLES',
				schema: 'information_schema',
				columns: [
					{ name: 'TABLE_NAME', property: 'name' },
					{ name: 'TABLE_SCHEMA', property: 'schema' }
				]
			});
			break;
		case 'pg':
			sql.setDialect('postgres');
			client = new db.Client(options.dsn);
			options.database = options.database || client.database;
			options.schema = options.schema || 'public';
			columns = sql.define({
				name: 'columns',
				schema: 'information_schema',
				columns: [
					{ name: 'table_schema', property: 'tableSchema' },
					{ name: 'table_name', property: 'tableName' },
					{ name: 'table_catalog', property: 'tableCatalog' },
					{ name: 'column_name', property: 'name' },
					{ name: 'ordinal_position', property: 'ordinalPosition' },
					{ name: 'data_type', property: 'type' },
					{ name: 'character_maximum_length', property: 'charLength' },
					{ name: 'column_default', property: 'defaultValue' },
					{ name: 'is_nullable', property: 'isNullable' }
				]
			});
			tables = sql.define({
				name: 'tables',
				schema: 'information_schema',
				columns: [
					{ name: 'table_name', property: 'name' },
					{ name: 'table_schema', property: 'schema' },
					{ name: 'table_catalog', property: 'catalog' }
				]
			});
			break;
	}

	if (!options.database) {
		callback(new Error('options.database is required if it is not part of the DSN'));
		return;
	}

	function openFile(next) {
		if (typeof(options.outputFile) === 'string') {
			fs.open(options.outputFile, 'w', options.mode, function(err, descriptor) {
				if (!err) {
					fd = descriptor;
				}

				next(err);
			});
		} else {
			if (options.outputFile === 1) {
				fd = 1; //stdout
			}

			process.nextTick(next);
		}
	}

	function connect(next) {
		log('debug', 'Attempting connection with DSN "' + options.dsn + '"');
		client.connect(next);
	}

	function writeHead(next) {
		log('info',
			'Starting generation against ' + options.database +
				(options.schema ? '.' + options.schema : '')
		);

		var functions = [];
		if (options.prepend) {
			functions.push(function(next) {
				write(options.prepend + options.eol, next);
			});
		}

		if (!options.omitComments) {
			functions.push(function(next) {
				var headerComment = '// autogenerated by ' + info.name +
					' v' + info.version + ' on ' + new Date();
				write(headerComment + options.eol, next);
			});
		}

		functions.push(function(next) {
			write('var sql = require(\'sql\');', options.eol, next);
		});

		async.series(functions, next);
	}

	function fetchTables(next) {
		getListOfTables(function(err, tables) {
			tableNames = tables;
			next(err);
		});
	}

	function processTables(next) {
		function writeTable(tableName, next) {
			var start = Date.now();
			log('info', 'Starting ' + options.schema + '.' + tableName + '...');
			getListOfColumns(tableName, function(err, columnData) {
				if (err) {
					next(err);
					return;
				}

				log('debug', '  Found ' + columnData.length + ' columns');

				var args = [],
					fullName = (options.schema || options.database) + '.' + tableName;

				if (!options.omitComments) {
					args.push('/**');
					args.push(' * SQL definition for ' + fullName);
					args.push(' */');
				}

				args.push('exports.' + camelize(tableName) + ' = sql.define({');
				args.push(options.indent + 'name: \'' + tableName + '\',');
				args.push(options.indent + 'columns: [');

				args.push(columnData.map(function(column) {
					var columnString = options.indent + options.indent + '{ ' +
						'name: \'' + column.name + '\'';

					if (options.camelize) {
						columnString += ', property: \'' + camelize(column.name) + '\'';
					}
					columnString += ' }';

					return columnString;
				}).join(',' + options.eol));

				args.push(options.indent + ']');
				args.push('});');
				args.push(options.eol);

				args.push(function(err) {
					if (!err) {
						log('debug', '  ...finished! (' + (Date.now() - start) + 'ms)');
					}

					next(err);
				});

				write.apply(null, args);
			});
		}

		async.eachSeries(tableNames, writeTable, next);
	}

	function writeTail(next) {
		if (options.append) {
			write(options.append, next);
		} else {
			process.nextTick(next);
		}
	}

	async.series([
		openFile,
		connect,
		writeHead,
		fetchTables,
		processTables,
		writeTail
	], function(appError) {
		if (appError) {
			log('error', appError);
		}

		stats.end = new Date();
		stats.elapsed = stats.end.getTime() - stats.start.getTime();
		if (fd && fd !== 1) {
			fs.close(fd, function(err) {
				if (err) {
					log('warn', 'Error closing file: ' + err);
				}

				log('info',
					'\nAll done! Wrote ' + stats.bytesWritten + ' bytes to ' +
						(options.outputFile || 'stdout') + ' in ' + stats.elapsed + 'ms',
					'yay!'
				);

				callback(appError, stats);
			});
		} else {
			callback(appError, stats);
		}
	});
};
